### ISSUE TITLE
Adya (Retail) - compliance check

### ISSUE THREAD

**Issue by sahil-ondc** [ONDC-Official/v1.2.0-logs#40] opened 2023-10-16 17:23 UTC
**on_search**

- /message/catalog must have required property 'bpp/fulfillments'
- /message/catalog/bpp~1providers/locations must have required property 'circle'
- /message/catalog/bpp~1providers/locations/time must have required property 'days'
- /message/catalog/bpp~1providers/locations/address must have required property 'street'

**on_select** 

- quote.price.value 2480.50 does not match with the total price breakup 2500.50

@kausic-eunimart

**Comment by bluecypher** [comment] 2023-10-20 11:15
## Flow 1

### Full catalog

- bpp/fulfillments is not required
- Delivery and Self-Pickup is not a valid fulfillment type in /bpp/providers/fulfillments
- category_id in /items and category in serviceability must be as per the subcategories defined in [enhanced subcategory list](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=1130527843)
- invalid HSN code for items in fashion domain in /items/descriptor/code
- return window of 45 mins is short for fashion domain; Is this intentional?
- attributes "net_quantity_or_measure_of_commodity_in_pkg", "imported_product_country_of_origin" and "multiple_products_name_number_or_qty" are not required in "@ondc/org/statutory_reqs_packaged_commodities"
- "month_year_of_manufacture_packing_import" must be in the correct format as defined in the contract
- "grey" is not a valid color enum in /items/tags/attribute/color refer to the enums [here](https://github.com/ONDC-Official/protocol-network-extension/tree/main/enums/retail)
- attribute enums must be the same as defined in the [repo](https://github.com/ONDC-Official/protocol-network-extension/blob/main/enums/retail/)(in lowercase)
- offer code "Disc_Pct" in /offers/descriptor/code is invalid; should be "disc_pct" (in lower case)
- attribute in tags for offers should be the same as defined in the contract
- timestamp is invalid attribute in /offers/time

### Incremental Catalog

**/search**

- city must be "\*" in incremental pull
- For 1-time incremental refresh: start_time < context.timestamp, end_time <= context.timestamp, end_time > start_time;

### Flow 2

**/select**

- is the geocoding of gps and area_code correct? Reverse geocoding shows different pincode

**on_select**

- @ondc/org/TAT can't be same for delivery and self-pickup in /fulfillments

**/on_init**

- payment details missing in payment object
- either one of percentage or amount needs to be provided in cancellation_terms

**/on_confirm**

- estimated pickup and delivery time ranges should be feasible and realistic
- additional_desc are not required in /start/instructions
- placeholder value should not be provided in long_desc

**/on_status**

- Invoice should only be provided once the order is shipped (i.e. Order-picked-up state and thereafter)
- actual pickup/delivery timestamps missing in the required states

### Flow 3

**/on_select (OOS)**

- error.message should only consist of comma delimited item ids

## Group B

**RET11 - catalog**

- upper & lower price range should not be provided if same
- duplicate ids can't be present in /categories
- min/max config for custom_group should be configured correctly, eg: "upto 1 option" should have configuration with min =0 and max= 1



@kausic-eunimart

**Comment by bluecypher** [comment] 2023-11-14 10:47
## Group A

### Flow 1

**/on_search (full_catalog)**

- search request initiated with context/city as std:080, but the on_search callback involves store in Delhi; The city code used in the search identifies the city where sellers have stores
- the grouping of variant is created for multiple attributes (gender/color/size/fabric), but SKUs are based on colour variant only
- brand and size_chart are missing (mandatory) attributes for category_id= "Shirts"

### Flow 2

- message_id should be unique for each unsolicited /on_status call

### Flow 3

- OOS item(s) should not be selected again; transaction_id should remain the same in /select and /select (OOS)

## Group B

### Grocery

- items/tags/attribute is not required if empty
- variant groupings are created without any attribute

### F&B

- PAN India serviceability is provided for F&B categories; Is this intended?
- multiple default customizations should not be provided for one parent custom group
- default customization should only be configured where atleast one customization is required (min=1)

### BPC and Electronics

- mandatory attributes should be provided as mentioned in the sheet [here](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=244000021)



@kausic-eunimart

**Comment by sharmasahil0331** [comment] 2023-11-29 15:50
**on_search_full_catalog_refresh**

- item.available.count should be either 99 (inventory available) or 0 (out-of-stock)
- item.maximum.count should be either default value 99 (no cap per order) or any other +ve value (cap per order)
- the grouping of variant is created for multiple attributes but SKUs are based on certain attributes only
- catalog quality related issues:
  - item descriptor shows different brand
  - invalid HSN code of the item
  - image of the item and colour attribute value mismatch
  - size_chart doesn't match with the item description

**select**

- provider.locations[0].id CANARAADYALOCATION71 mismatches in /on_search and /select

**init**

- Provider.locations[0].id mismatches in /select and /init

**on_init**

- provider_location.id mismatches in /on_search and /on_init

**confirm**

- /message/order/payment/@ondc~1org~1settlement_details/0 must have required property 'bank_name'
- /message/order/payment/@ondc~1org~1settlement_details/0 must have required property 'branch_name'
- provider.locations[0].id mismatches in /on_search and /confirm

**on_confirm**

- provider.locations[0].id mismatches in /on_search and /on_confirm
- store gps location /fulfillments[0]/start/location/gps can't change


@kausic-eunimart

**Comment by sharmasahil0331** [comment] 2023-12-07 18:39
### Flow 1

**on_search_full_catalog_refresh**

- /message/catalog/bpp/providers/items/quantity/available/count must be equal to one of the allowed values (99,0)
- invalid area_code provided in /message/catalog/bpp/providers/0/locations/address (CANARAADYALOCATION74) as per the provided gps 
- items having parent_item_id 'OGGKZTI5TNC6' should have variants for size_chart, brand, fabric, colour, gender as mentioned in categories array
- In case of message/catalog/bpp/descriptor/tags/bpp_terms/np_type 'MSN', atleast two providers should be provided (For logs prospective)


**on_search_inc_catalog_refresh**

- /message/catalog/bpp/providers/items/quantity/available/count must be equal to one of the allowed values (99,0)
- invalid keys 'locations', 'offers' provided message/catalog/bpp/providers
- timestamp should not change without any change in label in /message/catalog/bpp/providers/items/time
- change of '40' to '35' quantity/available/count is not a valid delta change

### Other Flows

**on_select**

- /message/order/quote/breakup/item/quantity/available/count must be equal to one of the allowed values (99,0)

**on_init**

- /message/order/cancellation_terms/fulfillment_state/descriptor/short_desc cannot be empty string

**on_status**

- /message/order/fulfillments/end/time/timestamp should be in end/time/range

@kausic-eunimart

**Comment by sharmasahil0331** [comment] 2023-12-14 19:23
## Flow 1

**on_search_full_catalog_refresh**

- items having parent_item_id 'OGGKZTI5TNC6' should have variants for size_chart, brand, fabric, colour, gender as mentioned in categories array
- invalid area_code provided in /message/catalog/bpp/providers/0/locations/address (CANARAADYALOCATION82) as per the provided GPS

**on_search_inc_catalog_refresh**

-  message/catalog/bpp/providers/items/time/timestamp should only update in case of change in label update

**on_status**

- /message/order/fulfillments/start/time/timestamp cannot match /message/order/fulfillments/end/time/range/start/timestamp

## Flow 4

**on_cancel**

- /message/order/fulfillments/1/end/time/range/start must be string
- /message/order/fulfillments/1/start/time/timestamp must be string

## suggestive changes

**on_search_full_catalog_refresh**

- short_desc and long_desc should be unique in message/catalog/bpp/providers/descriptor

## Note

Kindly submit logs with different Buyer/Seller NP

@kausic-eunimart

**Comment by bluecypher** [comment] 2023-12-26 12:12
### Order flow for customizable item(s) should be submitted for verification

## Flow 1

**/search**

- static terms are not yet finalised; placeholder url value should not be provided

**/on_search**

- "40" is not a valid size enum for category_id = "Formal Shoes"
- mandatory attributes are missing for item id: "IMPFS5236"
- variant_group: PXZOA5F5W3BS has no definition in the catalog in /categories
- grouping of variant is created for multiple attributes (gender/color/size/fabric), but SKUs are based on specific attributes only
- "camel" is not a valid colour attribute value
- price value can't be greater than maximum_value; eg- check item: "OBAPHBHC8WOB"

**/search (incremental)**

- buyer app finder fee is increased; Is this intended? Modifying BAPFF is not recommended in incremental search since bap terms are accepted in full catalog

## Flow 2

**/on_init**

- buyer app finder fee is set as 5% in /payment; however, BAP finder fee was changed to 6 percent in /search (incremental);
- cancellation fee is being charged at pending and packed state as well; is this intended? (also, cancellation_terms is not a part of phase 1; can be removed for now)

**/on_status**

- estimated pickup/delivery time ranges should not be changed in interim calls

**/on_track**

- gps value can't be null; should be either empty string or attribute should be removed

## Flow 4

- packing/delivery fees should not be charged when order is cancelled before packing

#### - there are some repeated issues, please check the previously identified issues

#### - pls check mandatory attributes and enum values for GROUP B catalogs


@kausic-eunimart

**Comment by kausicm30** [comment] 2023-12-27 06:57
/on_status

estimated pickup/delivery time ranges should not be changed in interim calls

**Comment by sahil-ondc** [comment] 2024-01-03 09:16
## Flow 1

**on_search_full_catalog_refresh**

- /message/catalog/bpp/providers/locations/circle should not be provided in case of PAN India serviceability

**on_search_inc_catalog_refresh**

- /message/catalog/bpp/providers/time/timestamp should change only in case of change in its label

## Flow 2

**on_init**

- /message/order should not have property 'provider_location' (Deprecated)
- cancellation_terms is not a part of phase 1; can be removed for now

**on_confirm**

- /message/order/tags/1/list/1/value must NOT have fewer than 1 characters

## Note

Kindly submit logs with different Buyer/Seller NP

@kausic-eunimart

**Comment by BLR-0118** [comment] 2024-01-09 13:03
duplicate of #490, hence closing

**Closed by BLR-0118** 2024-01-09 13:03 UTC
