### ISSUE TITLE
Costbo - compliance check 

### ISSUE THREAD

**Issue by sahil-ondc** [ONDC-Official/v1.2.0-logs#172] opened 2023-11-28 15:07 UTC
**on_search_full_catalog_refresh**

- /message/catalog/bpp/providers/items/quantity/available/count must be equal to one of the allowed values (99,0)
- invalid timestamp format in /message/catalog/bpp~1providers/locations/time

**search_inc_refresh**

- /message/intent/payment/@ondc~1org~1buyer_app_finder_fee_amount must be string
- Timestamp not in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) Format
- context/city should be \* while sending search_inc_catalog request

**on_search_inc_refresh**

- bpp/fulfillments sent in payload shoulnd't be part of /on_search_inc_refresh api
- bpp/descriptor sent in payload shoulnd't be part of /on_search_inc_refresh api
- location should be sent only if there is any change in delta
- Similar Item as in /on_search_full_catalog_refresh api call, item id - 4cbdd9c08c614d39884e40b1dd279341
  a

@AnanthBo

**Comment by sharmasahil0331** [comment] 2023-11-28 15:12
Kindly submit Flow4 and Flow5 as well.

**Comment by AnanthBo** [comment] 2023-11-29 08:16
We are currently using off network logistics.  So we will provide flow 4.

**Comment by sharmasahil0331** [comment] 2023-12-05 18:02
**on_search_full_catalog_refresh**

- placeholder values should not be provided for ex (categories)
- message/catalog/bpp/providers items should have valid timestamp format RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ)

**on_search_inc_catalog_refresh**

- keys with empty array should not be provided (fulfillments,locations,categories)
- message_id should be unique in case of search_inc_mode is start

### Note

- Kindly provide on_search with variants as well

@AnanthBo

**Comment by AnanthBo** [comment] 2023-12-21 00:46
@sahil-ondc 
Thank you for the comments.  Please review at the earliest.  Have fixed the requested comments of #172 in the  #297   (which has New RSF commit & Retail + IGM fixes)
https://github.com/ONDC-Official/v1.2.0-logs/pull/297
#297 for RSF logs. - New +. Fixed push of #286 & #172 issue comments.

**Comment by AnanthBo** [comment] 2023-12-22 07:24
@sahil-ondc     Could you please review and give us a confirmation

**Comment by AnanthBo** [comment] 2023-12-22 10:33
@bluecypher ,   could you please help us on this review.

**Comment by sahil-ondc** [comment] 2023-12-22 12:11
## Flow 1

**on_search_full_catalog_refresh**

- /message/catalog/bpp/providers/locations/time/timestamp cannot be greater than context/timestamp
- /message/catalog/bpp/providers/items/time/timestamp cannot be greater than context/timestamp
- /message/catalog/bpp/providers/items/id cannot be same as /message/catalog/bpp/providers/items/parent_item_id

## Other Flows

**on_select**

- /message/order/quote/breakup/item/quantity/available/count should be in stringified integer format, it cannot be float or decimal

@AnanthBo

**Comment by AnanthBo** [comment] 2023-12-26 04:29
@sahil-ondc ,  The above is for retail logs.  Can i assume the IGM logs are approved ?  RSF logs are approved ? .   How or when i will get the approved information ?

**Comment by sahil-ondc** [comment] 2023-12-26 04:58
@AnanthBo This issue is regarding the Retail Seller Application logs only, please check RSF, IGM issue board as well.

**Comment by AnanthBo** [comment] 2023-12-26 06:31
@sahil-ondc ,  Updated the Retail Logs for the above correction on On_select & On_search.  Please let me know your comments at the earliest.

**Comment by sahil-ondc** [comment] 2023-12-27 04:35
@AnanthBo Can you link the latest MR here in which you have fixed the issues ?

**Comment by AnanthBo** [comment] 2023-12-27 05:07
@sahil-ondc   PR #297    Brought in the retail fixes along with RSF.

**Comment by sahil-ondc** [comment] 2023-12-27 07:39
Please check https://github.com/ONDC-Official/v1.2.0-logs/issues/172#issuecomment-1867614879
These issues are stil open

@AnanthBo

**Comment by AnanthBo** [comment] 2023-12-27 10:01
@sahil-ondc   ,  Below Pull has the Retail logs. requested for recent comments.  Please review & let me know.

https://github.com/ONDC-Official/v1.2.0-logs/pull/370
Retail latest repush & IGM repush the latest test logs

**Comment by CharanpreetChawla** [comment] 2023-12-29 06:53
## Flow 1 
**/on_search**
- Categories not present even when parent_item_id is present in items

## Flow 2
**/on_select**
- slots and tracking are not available as per flow
- message.fulfillments.type is not present. (Delivery/self-pickup)

**/on_init**
- message.order.items[n].parent_item_id not present. (but present in on_search).

**/on_confirm**
- message.order.items[n].parent_item_id not present. (but present in on_search).
- message.order.fulfillments.tracking is "true". (but false in /on_select, /on_init)

**Comment by AnanthBo** [comment] 2023-12-29 10:27
@CharanpreetChawla    Can you please call 9845570864 or provide your number ?  1.  would like to understand two  comments &.  2.  would like to explain as you are looking at the old commit.

**Comment by CharanpreetChawla** [comment] 2023-12-29 11:36
@AnanthBo,
1. Acknowledged, can proceed with the same
...
3. Please do resubmit the logs for the rest of flow with the related /search and /on_search as it was mentioned earlier comments about the problems in /on_select

**Comment by AnanthBo** [comment] 2023-12-29 17:32
@CharanpreetChawla     Submitted the logs with PR #403. https://github.com/ONDC-Official/v1.2.0-logs/pull/403

Please review and let us know your comments.

**Comment by sahil-ondc** [comment] 2024-01-02 17:57
## Flow 1

**on_search_full_catalog_refresh**

- /context/bpp_uri should not end with '/'
- /message/catalog/bpp/providers/id should not match message/catalog/bpp/providers/locations/id
- /message/catalog/bpp/providers/items/tags cannot have values together 'veg', 'nonVeg', 'egg'
- /message/catalog/bpp/providers/items/quantity/unitized/measure should be of the 'unit', 'dozen', 'kilogram', 'tonne', 'litre', 'millilitre'
- @ondc/org/contact_details_consumer_care should be in the format 'name,email,contactno', invalid value provided 'Himachal Jams, marketing@costbo.com, '

## Flow 2

**on_select**

- City code mismatch in /search and /on_select

**on_init**

- /message/order should not have property 'provider_location'
- /message/order/quote/breakup/item/quantity/available/count should be in stringified integer format, it cannot be float or decimal
- /message/order/quote/breakup/item should be as per the API contract

**on_status**

- invalid timestamp provided in /message/order/fulfillments/end/time

@AnanthBo

**Comment by AnanthBo** [comment] 2024-01-03 13:01
@sahil-ondc  Addressed the comments above.  Please review #437  https://github.com/ONDC-Official/v1.2.0-logs/pull/437

**Comment by AnanthBo** [comment] 2024-01-04 14:31
@sahil-ondc ,   Can you please advise on the logs.

**Comment by AnanthBo** [comment] 2024-01-06 07:12
@sahil-ondc   would you be able to suggest comments -  today please.  So we can make progress over the weekend.

**Comment by sahil-ondc** [comment] 2024-01-06 08:49
## Flow 1

### on_search_full_catalog_refresh

- item_id: da1da524af79485eb95893cf5c98cc82 should have veg_nonveg one of the 'veg', 'non_veg', 'egg' in bpp/providers[0]
- location in serviceability construct should be one of the location ids bpp/providers[0]/locations
- location in serviceability construct should be one of the location ids bpp/providers[1]/locations

## Flow 2

### on_select

- /message/order/quote/breakup/item/quantity available and maximum count logic should remain same as provided in on_search
  (99, 0)

### on_confirm

- provider.locations[0].id mismatches in /on_search and /on_confirm

### on_status

- /message/created_at should remain same as in /confirm call, when order was created
- /message/billing/updated_at should remain same as in /init call


@AnanthBo

**Comment by AnanthBo** [comment] 2024-01-06 10:58
Thank you Sahil.  Will get back with fixes.

**Comment by AnanthBo** [comment] 2024-01-08 09:39
@sahil-ondc     PR#475 submitted.  https://github.com/ONDC-Official/v1.2.0-logs/pull/475
Please review and approve.

**Comment by AnanthBo** [comment] 2024-01-10 09:11
@sahil-ondc ,  could you please review and provide update.

**Comment by sahil-ondc** [comment] 2024-01-10 17:11
## Flow 1

### search_full_catalog_refresh

- /message/intent/fulfillment/end/location must have required property 'address'

### on_search_full_catalog_refresh

- context/timestamp of search call '2023-07-25T15:49:02.698Z', how on_search has been sent now with context/timestamp '2024-01-08T08:52:15.608Z'
- category in serviceability construct should be one of the category ids bpp/providers[0]/items/category_id

## Flow 2

### on_init

- billing issues
  - Key 'phone' mismatch: 09845570864 !== 9845570864


@AnanthBo

**Comment by AnanthBo** [comment] 2024-01-12 05:38
@sahil-ondc ,  Thanks for your comments.  Have fixed them.     
New PR#519 .   could you please review.

**Comment by AnanthBo** [comment] 2024-01-16 04:00
@sahil-ondc    could you please provide an update today.

**Comment by sahil-ondc** [comment] 2024-01-16 18:29
## Flow 1

### on_search

- value should be "country" (code:"unit") for type 12 (PAN India) in /bpp/providers/tags
- /message/catalog/bpp/providers/items/@ondc/org/time_to_ship should be in valid format 'ISO 8601'
- how item 'Silk thread hook jhumka' be in category 'Beverages'

### Flow 2

### on_confirm

- /message/order/fulfillment/start/time range cannot be same as /message/order/fulfillment/end/time

### on_status

- /message/order/fulfillment/start/time and /message/order/fulfillment/end/time should not change, should be same as provided in on_confirm

@AnanthBo

**Comment by AnanthBo** [comment] 2024-01-17 12:05
@sahil-ondc    This request. {{how item 'Silk thread hook jhumka' be in category 'Beverages'}}.  >>. Please ignore, as this is a  preprod test environment to test various categories we have assigned it.   

Will submit rest of the fixes today

**Comment by AnanthBo** [comment] 2024-01-18 03:38
@sahil-ondc ,   Retail logs have been submitted. https://github.com/ONDC-Official/v1.2.0-logs/pull/571
Please review and let us know.

**Comment by AnanthBo** [comment] 2024-01-19 11:33
@sahil-ondc ,  could you please review & let us know

**Comment by sahil-ondc** [comment] 2024-01-22 20:33
## Flow 1

### on_search

- Beauty & Hygiene and Gourmet & World Foods are deprecated
  `https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=0`
- /message/catalog/bpp/providers/items/tags[1]/list/code: veg on this value is yes when item is 'Meena Bead Rakhi'
- The contact details for consumer care (@ondc/org/contact_details_consumer_care) should be in the format "name,email,contactno" in /bpp/providers[0]/items
- /message/catalog/bpp/providers/items/time/timestamp is greater than context/timestamp

## Flow 2

### on_confirm

- /message/order/fulfillment/start/time/range/start cannot be same as /message/order/fulfillment/end/time/range/end

@AnanthBo

**Comment by AnanthBo** [comment] 2024-01-24 12:26
@sahil-ondc ,    PR#631 has been pushed for RET10.  Please review & provide comments at the earliest pls.

**Comment by sahil-ondc** [comment] 2024-01-27 14:11
## Flow 1

### on_search

- /message/catalog/bpp/providers/location/address/street cannot be empty string ""
- /context/city should be as per provided area_code in /message/catalog/bpp/providers/location/address
- /message/catalog/bpp/providers/items/descriptor/code should be valid EAN number in case of code 1 as per API contract
  `https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.yr8id0fwawkv`
- /message/catalog/bpp/providers/items/@ondc/org/statutory_reqs_prepackaged_food should not have placeholder values

## Flow 2

### select

- Buyer selects multiple items for checkout as per the sheet
  `https://docs.google.com/spreadsheets/d/1JZV6ZQzXcHUsOwegGtArX3DdIXYIy3gxkhQ00q7kICc/edit#gid=1367601795`

### on_select

- delivery line item must be present in quote/breakup (if location is serviceable)

### on_status

- un-solicited on_statuses must have different message_id

## Flow 3

### on_select (out-of-stock)

- /error/message should be as per the API contract
  `https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.w0p6bcyawc9u`

## Flow 4

### on_cancel

- /message/order/tags should have 'quote_trail' as per the API contract
  `https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.yzl8pn3ixxec`

@AnanthBo

**Comment by AnanthBo** [comment] 2024-02-02 04:42
@sahil-ondc  #683  has been submitted yesterday.  Can you please review & approve.

**Comment by AnanthBo** [comment] 2024-02-02 08:30
@sahil-ondc  @bluecypher .    PR #700   has been submitted with corrections suggested by Sandeep Shahi.   Let us know your comments at the earliest.

**Comment by AnanthBo** [comment] 2024-02-04 16:59
@sahil-ondc  @bluecypher  PR#712  has been submitted to remove the old retail logs.

**Comment by AnanthBo** [comment] 2024-02-15 03:20
@sahil-ondc  @bluecypher ,  

PR #826   has been submitted with flow6 new requirement.  (6c we have a exception from supriyo, as we are dealing with Grocery & not Fashion industry). This logs is for RET10.

**Comment by sahil-ondc** [comment] 2024-02-17 19:04
## Flow 1

### on_search_full_catalog_refresh

- /message/catalog/bpp/descriptor/tags/bpp_terms must have property np_type (ISN, MSN)
- either one of '@ondc/org/statutory_reqs_packaged_commodities', '@ondc/org/statutory_reqs_prepackaged_food' should be provided in /message/catalog/bpp/providers/items (as per the sheet)
  `https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=0`
- @ondc/org/contact_details_consumer_care contactno should consist of 10 or 11 digits without any spaces or special characters in /bpp/providers[0]/items
- remove formatting from /message/catalog/bpp/descriptor/long_desc
- bpp_terms should be provided in /message/catalog/bpp/descriptor/tags not in /message/catalog/bpp/providers/descriptor/tags
- /message/catalog/bpp/providers/categories/id should be alphanumeric & up to 12 characters

## Flow 3

### on_select

- /message/order/provider must have required property 'locations'

### on_select (out-of-stock)

- logs should be provided with items in stock until order-delivered as per the roll-out sheet
  `https://docs.google.com/spreadsheets/d/1JZV6ZQzXcHUsOwegGtArX3DdIXYIy3gxkhQ00q7kICc/edit#gid=1367601795`

## Flow 4

### on_cancel

- /message/order/payment/uri should be same as provided in /confirm

## Other Flows

### on_select

- /message/order/provider must have required property 'locations'

### on_confirm

- provider_tax_number (pan number of merchant) should be provided in /tags/bpp_terms

@AnanthBo

**Comment by sahil-ondc** [comment] 2024-02-21 18:19
## Flow 1

### on_search_full_catalog

- item_id: f61e10aa600b412c9233caf0a8fae364 should have veg_nonveg one of the 'veg', 'non_veg' in bpp/providers[0]

## Flow 2

### on_status (accepted)

- /message/order/fulfillment/state/descriptor should not be 'packed' in case of order/state 'Accepted' (check mapping)
  `https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit`

## Flow 3

### on_select (out-of-stock)

- /message/orde/quote/breakup/@ondc/org/title_type 'discount' should only be provided in case of positive value

## Flow 4

### on_cancel

- /message/order/fulfillments/tags/cancel_request should have 'precancel_state'

## Flow 6

### on_status (buyer-before-return)

- Transaction log should contain the partial cancellation state

## common

- /message/orde/quote/breakup/@ondc/org/title_type 'discount' should only be provided in case of positive value

@AnanthBo

**Comment by AnanthBo** [comment] 2024-02-24 08:20
@sahil-ondc     

https://github.com/ONDC-Official/v1.2.0-logs/pull/929 

We have submitted Retail. PR#929. - dated Feb24 - Full Set Flow1 - Flow6 - RET10.
Please review & possibly provide a good news !!

**Comment by bluecypher** [comment] 2024-02-28 10:10
**/on_confirm**

- PCC is set as "value"; is this the value for merchant order no./pos no.
- delivery TAT must be provided in /fulfillment/@ondc/org/TAT

**/on_status**

- invoice should only be provided once the order is picked and thereafter
- "Packed", "Out-for-delivery" states are missing

**/on_cancel**

- contact/phone should be of 10/11 digits; check other APIs for similar issues ("on_cancel" and "on_update")
- why are delivery/packing/misc fees being charged when order is cancelled at pending state
- invalid code cancelled_by in /tags/cancel_request; should be "initiated_by" instead

**/on_cancel (RTO)**

- RTO delivery charges in quote_trail should also be present as part of quote/breakup
- invalid code cancelled_by in /tags/cancel_request; should be "initiated_by" instead
- cancellation reason id mismtaches in fulfillments/tags/cancel_request and /cancellation ("015" vs "018")

**/on_update (part cancel/liquidated)**

- quote_trail should be updated correctly; item and discount should be present as separate quote_trail line items

**/update (FYI Refund)**

- update call with refund info is missing


@AnanthBo

**Comment by AnanthBo** [comment] 2024-03-02 09:27
Sandeep,  @bluecypher  Submitted PR#992 RET10 full set for your review.

**Comment by bluecypher** [comment] 2024-03-07 04:27
**/on_status**

- order state must be "In-progress" when fulfillment state is "Packed"; check order and fulfillment state mapping [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.ii1xl1f08zho)
- invoice should be provided once the order is picked and thereafter; pls check for any similar system breaks
- settlement_timestamp in /"@ondc/org/settlement_details" should only be provided when the amount is settled by the collector; won't be present here

**/on_cancel (RTO)**

- updated_at timestamp for precancel_state (Out-for-delivery here) is not captued correctly; the timestamp provided is even before the order is picked

**/on_status (RTO-Disposed)**

- order/updated_at timestamp should be updated correctly as per the change in order object



#### Ques: Are multiple fulfillment supported? If yes, how will multiple fulfillment ids be created?



@AnanthBo

**Comment by BLR-0118** [comment] 2024-03-10 09:10
Flow 1
====
1. /on_search (full):
- variant names should be more meaningful for the end buyer (as buyer apps will display this name);
- locations.address needs to be properly defined (locality can't be Bengaluru & entire address has been put into street);
- gps coords should be truncated to 6 decimals (which gives precision up to 100mm);
- considering that radial distance of earth is ~6000km, what does radius of 3000km here mean?
- many items seem to have the same EAN code 9146733310256: meaning?
- store timings per the new format is required;

2. /on_search (inc):
- pls share inc update for item going out-of-stock;

Flow 2
====
1. /on_select:
- what's the logic used to compute TAT of 5 days for delivery between 560053 (store loc) & 560103 (buyer loc)?
- quote is incorrect:
- item 7402* has price of 299 (as per catalog) but quote has MRP of 500;
- "discount" is for cart-level discounts, split across items & applied to selling price;
- same with item f61*;

2. /on_confirm:
- fulfillment TAT is 5 days but pickup slot is between 2nd & 4th Mar, while delivery slot is between 2nd & 7th Mar: how?

3. /on_status*:
- routing.type is reqd to allow buyer apps to differentiate between P2P & P2H2P;
- in /on_status_packed: fulfillment state "Packed" mapped to order state "Accepted" is incorrect;

**Comment by BLR-0118** [comment] 2024-03-10 10:22
@AnanthBo - pls resubmit flows 1, 2 & 6

**Comment by AnanthBo** [comment] 2024-03-15 06:47
@BLR-0118    As requested, we are attaching the logs for Flow 1, 2 and 6.  
PR# 1116. https://github.com/ONDC-Official/v1.2.0-logs/pull/1116

**Comment by AnanthBo** [comment] 2024-03-26 10:27
@BLR-0118 ,  Supriyo. We have resubmitted 1, 2 & 6 as per your requests.    OPS test have cleared all the scenarios as well.    Please give us a go ahead for BetaProd.

**Comment by BLR-0118** [comment] 2024-03-27 05:41
Flow 1
====
1. /on_search:
- why is EAN code not being used for items?
- catalog has items in 1 category; however, category mapping is inconsistent, e.g. item 0106d139963743aea8598533de03feab & d4e6ff6371044c49965c4c48773961c5 are both marmalade but category is different;

**Comment by BLR-0118** [comment] 2024-03-27 06:06
Flow 2
====
1. /on_confirm:
- TAT is 2 days, pickup slot is between 03:07 (15th) & 02:52 (16th), while delivery slot is between 03:52 (15th) & 02:52 (15th): this doesn't add up;

Flow 6
====
1. seller invoice is being added in /on_update (part cancel); typically, this is done at Order-picked-up so that additional part cancels can be considered;
2. since these are resaleable items, why isn't return with pickup being enabled?

**Comment by BLR-0118** [comment] 2024-03-27 06:06
@AnanthBo

**Comment by AnanthBo** [comment] 2024-03-27 06:08
@BLR-0118   Sir,    Response to your comment:

We are a MSN seller for Brands and this is our sample (replica of original) seller for approval.   We have 100s of existing D2C brands which will be thoroughly verified, corrected  and updated by our operations team  as per ONDC requirement  & Brands Input  - once our RET10 is validated.   Eventually into other Categories. 

1). We have 4 options.  EAN , HSN & others.   We provide a drop down for the brand to enter any one of the options.    Brand has given us  HSN code.   They deal with Jams only.  & hence the HSN code is same for all their items.   This is acceptable as per contract. 

2).  Agree, for testing and implementation perspective we have added to similar products into different categories.   This is dynamic based on our product table. (This is a drop parameter for brand to choose the category &  We also have approval team for live products thats being added before getting live).      This is a demo (duplicate of original)  seller & We will fix this before we go live .   This brand will not go live.   This will stay in preprod environment for testing.    So please give a exception to this comment.

I would like to give a demo of our system in detail, if you could spare some time  & also take inputs for improvement.

**Comment by AnanthBo** [comment] 2024-03-27 06:50
@BLR-0118    For Flow 2 & Flow 6,   have sent a email for your review. Please let us know.

**Comment by AnanthBo** [comment] 2024-03-27 18:28
@BLR-0118 .  Thanks Supriyo for your comments.    Please confirm if the below is appropriate output based on our discussion.  

same city Logistics
timeToShip ⇒ 1D
+0 ordered - Mar27, 10 am
+1 day -  Pickup Slot:     Mar28, 2 pm  - Mar 28, 7pm
+2 day - Delivery Slot:   Mar29, 10am -   Mar 29, 2pm.

**Comment by AnanthBo** [comment] 2024-03-28 21:09
@BLR-0118    please review our logs .  this logs addresses comments on the below as requested

PR# 1227 

COSTBO-comments from Supriyo addressed for flow1-2-6
1.  flow1 - Onsearch - Grocery tagged to EAN
2.  Flow6 - onupdate- partial CANCEL to remove the Invoice URL & add from "order-picked-up"
3.  flow2 - onconfirm - TAT 2D ,  pickup slot, delivery slot corrected.

**Comment by BLR-0118** [comment] 2024-03-30 15:09
logs cleared for v1.2.0 (RET10)

**Closed by BLR-0118** 2024-03-30 15:09 UTC

**Comment by BLR-0118** [comment] 2024-03-30 15:15
logs cleared for v1.2.0 (RET16)

**Comment by AnanthBo** [comment] 2024-03-30 16:22
@BLR-0118   @sahil-ondc  @sandeepshahi  Thank you Supriyo, Sahil and Sandeep  for clearing our RET10 & RET 16 logs.
