### ISSUE TITLE
COSTBO Seller App - compliance check

### ISSUE THREAD

**Issue by CharanpreetChawla** [ONDC-Official/v1.2.0-logs#372] opened 2023-12-27 12:13 UTC
## Flow 1 
**/on_search**
- Categories not present even when parent_item_id is present in items

## Flow 2
**/on_select**
- slots and tracking are not available as per flow
- message.fulfillments.type is not present. (Delivery/self-pickup)

**/on_init**
- message.order.items[n].parent_item_id not present. (but present in on_search).

**/on_confirm**
- message.order.items[n].parent_item_id not present. (but present in on_search).
- message.order.fulfillments.tracking is "true". (but false in /on_select, /on_init)

**Comment by BLR-0118** [comment] 2023-12-30 07:03
I'll be reviewing all retail & logistics logs for signoff
@CharanpreetChawla

**Comment by sahil-ondc** [comment] 2023-12-31 07:59
@BLR-0118 This was the duplicate issue which @CharanpreetChawla has created, 
Issue for Costbo already exists https://github.com/ONDC-Official/v1.2.0-logs/issues/172

**Comment by AnanthBo** [comment] 2023-12-31 11:41
Yes.  #172 is our previous & 35 days+ old - "COSTBO  Retail Compliance check.  @sahil-ondc  @BLR-0118  @CharanpreetChawla

**Comment by BLR-0118** [comment] 2024-01-01 09:57
duplicate of #172

**Closed by BLR-0118** 2024-01-01 09:57 UTC
