### ISSUE TITLE
Chattybao (RET11 : Seller App ) - compliance check

### ISSUE THREAD

**Issue by Jagannath-wits** [ONDC-Official/v1.2.0-logs#1184] opened 2024-03-22 11:50 UTC
# Flow 1
## Search Full Catalog Refresh

- **Schema Error 0**: `/context/action` must be equal to constant (search)
- **Action Error**: `context.action` should be search

## On Search Full Catalog Refresh

- **Schema Error **: `/message/catalog/bpp~1providers/0/@ondc~1org~1fssai_license_no` must NOT have fewer than 14 characters
- **Schema Error **: `/message/catalog/bpp~1providers/0/categories/1` must have required property 'parent_category_id'
- **Schema Error**: `/message/catalog/bpp~1providers/0/items/0/category_ids/0` format of category_ids must be followed as per API contract
- **Schema Error**: `/message/catalog/bpp~1providers/0/tags/0/list/0/value` min_value must be number with exactly two decimal places
- **Schema Error**: `/message/catalog/bpp~1providers/1/items/0/category_ids/0` format of category_ids must be followed as per API contract
- **Schema Error**: `/message/catalog/bpp~1providers/1/tags/0/list/0/value` min_value must be number with exactly two decimal places
- **BPP/Providers[1]/Items[5]/Descriptor**: `short_desc` and `long_desc` should not be provided as empty string `""` in `/message/catalog/bpp/providers[1]/items[5]/descriptor`
-  Duplicate seq: 0 in category_ids in prvdr0item9
-  Duplicate seq: 1 in category_ids in prvdr0item10
-  Duplicate seq: 2 in category_ids in prvdr0item11
-  Duplicate seq: 3 in category_ids in prvdr0item12
-  Items should have category_ids one of the Catalog/categories/id
- Item_id: 0ae6b110-c407-11ee-8a4f-03de6b9a1857:MxSDrFVEJz5n7KenwtGygL should have custom_group_id one of the ids passed in categories bpp/providers[2]
- Value in catalog/items3/tags3/config/list/ should be one of the catalog/category/ids

## Search Incremental Refresh

- **Schema Error **: `/context/action` must be equal to constant (search)
- **Action Error**: `context.action` should be search

## On Search Incremental Refresh

- **Schema Error **: `/message/catalog/bpp~1providers/0/items/0/category_ids/0` must match pattern `"^[a-zA-Z0-9]{1,12}:[a-zA-Z0-9]{1,12}$"`
- **Schema Error **: `/message/catalog/bpp~1providers/0/items/1/category_ids/0` must match pattern `"^[a-zA-Z0-9]{1,12}:[a-zA-Z0-9]{1,12}$"`
- **Prvdr0Item0CtgryId0**: Item0 should have category_ids one of the Catalog/categories/id
- **Prvdr0Item1CtgryId0**: Item1 should have category_ids one of the Catalog/categories/id

# Flow 2
## Select

- **Location ID**: Location_id should be same for the item d517b490-0aab-11ee-8ac0-3b78afefe16f:MxBP2YIbdEmMcVM64qEvN1:DC as in on_search
- **Location ID**: Location_id should be same for the item 7f99ede0-da2a-11ee-9f48-0f9239d4a820:MxBP2YIbdEmMcVM64qEvN1:C:d517b490-0aab-11ee-8ac0-3b78afefe16f as in on_search

## On Init

- **Quantity Error**: Extra attribute Quantity provided in quote object i.e not supposed to be provided after on_select so invalid quote object

## Confirm

- Same as above

## On Confirm

- **Payment Object Mismatch**: Payment object mismatches in /confirm & /on_confirm

## On Status Pending

- Missing payload

# Flow 3

- Same as above

# Flow 5
## Select

- **Location ID**: Location_id should be same for the item d517b490-0aab-11ee-8ac0-3b78afefe16f:MxBP2YIbdEmMcVM64qEvN1:DC as in on_search
- **Location ID**: Location_id should be same for the item 7f99ede0-da2a-11ee-9f48-0f9239d4a820:MxBP2YIbdEmMcVM64qEvN1:C:d517b490-0aab-11ee-8ac0-3b78afefe16f as in on_search
- **Location ID**: Location_id should be same for the item 85b86580-da2a-11ee-9f48-0f9239d4a820:MxBP2YIbdEmMcVM64qEvN1:C:d517b490-0aab-11ee-8ac0-3b78afefe16f as in on_search
- **Location ID**: Location_id should be same for the item 85b86580-da2a-11ee-9f48-0f9239d4a820:MxBP2YIbdEmMcVM64qEvN1:C:d517b490-0aab-11ee-8ac0-3b78afefe16f as in on_search
- **Item4id Parent Item ID**: /message/order/items/parent_item_id cannot be duplicate if item/id is same

## On Status Pending

- Missing payload

## On Status Packed

- **Transaction ID Consistency**: Transaction Id should be same from /select onwards
- **Order ID Mismatch**: Order id in /confirm and /on_status_packed do not match
- **Timestamp Mismatch**: Created At timestamp for /on_status_packed.message.order should be equal to context timestamp at confirm
- **Timestamp Order**: Timestamp for /on_confirm api cannot be greater than or equal to /on_status_packed api

## On Status Picked

- **Transaction ID Consistency**: Transaction Id should be same from /select onwards
- **Order ID Mismatch**: Order id in /confirm and /on_status_picked do not match
- **Timestamp Mismatch**: Created At timestamp for /on_status_picked should be equal to context timestamp at confirm
- **Timestamp Order**: Timestamp for /on_confirm api cannot be greater than or equal to /on_status_picked api

## On Status Out for Delivery

- **Transaction ID Consistency**: Transaction Id should be same from /select onwards
- **Order ID Mismatch**: Order id in /confirm and /on_status_out-for-delivery do not match
- **Timestamp Mismatch**: Created At timestamp for /on_status_out-for-delivery should be equal to context timestamp at confirm
- **Timestamp Order**: Timestamp for /on_confirm api cannot be greater than or equal to /on_status_out-for-delivery api

# On Cancel Errors

- **Schema Error **: `/message/order/fulfillments/1/end` must have required property 'location'
- **Schema Error **: `/message/order/fulfillments/1/end` must have required property 'person'
- **Schema Error **: `/message/order/fulfillments/1/end` must have required property 'contact'
- **Schema Error **: `/message/order/fulfillments/1/end/time` must have required property 'range'
- **Schema Error **: `/message/order/fulfillments/1/tags/0/list/4/code` must be equal to one of the allowed values (reason_id, initiated_by, fulfillment_state, updated_at, retry_count, rto_id, id, currency, value, type)
- **Schema Error **: `/message/order/fulfillments/1/tags/1/list/4/code` must be equal to one of the allowed values (reason_id, initiated_by, fulfillment_state, updated_at, retry_count, rto_id, id, currency, value, type)
- **Schema Error **: `/message/order/fulfillments/1/tags/2/list/4/code` must be equal to one of the allowed values (reason_id, initiated_by, fulfillment_state, updated_at, retry_count, rto_id, id, currency, value, type)
- **Schema Error **: `/message/order/fulfillments/1/tags/3/list/4/code` must be equal to one of the allowed values (reason_id, initiated_by, fulfillment_state, updated_at, retry_count, rto_id, id, currency, value, type)
- **Schema Error **: `/message/order/fulfillments/1/tags/4/list/4/code` must be equal to one of the allowed values (reason_id, initiated_by, fulfillment_state, updated_at, retry_count, rto_id, id, currency, value, type)
- **Schema Error **: `/message/order/fulfillments/1/tags/5/list/4/code` must be equal to one of the allowed values (reason_id, initiated_by, fulfillment_state, updated_at, retry_count, rto_id, id, currency, value, type)
- **Invalid Quote Trail Prices**: Quote_trail price and item quote price sum for on_cancel should be equal to the price as in on_confirm

# Flow 6-b and 6-c
Please provide labelled flows for reverse QC (6-b) and liquidation (6-c) with all on_update calls as on_update approved is missing for 6-b

@venkat77777

**Comment by venkat77777** [comment] 2024-03-22 12:48
@Jagannath-wits as per the contract doc customizations, short_desc and long_desc are not present
```  "id":"C1",
              "descriptor":
              {
                "name":"New Hand Tossed"
              },
```

**Comment by venkat77777** [comment] 2024-03-22 12:51
@Jagannath-wits display sequence of an item will be as per the menu, right? If i have two menus and 5 items each, there'll be 0th  sequence in both menus, right?  as both menus are different and to be displayed in that order?

**Comment by Jagannath-wits** [comment] 2024-03-22 12:51
@venkat77777 yes, please disregard that

**Comment by Jagannath-wits** [comment] 2024-03-22 12:53
> customizations

yes this will be string only

**Comment by venkat77777** [comment] 2024-03-22 12:53
@Jagannath-wits `Items should have category_ids one of the Catalog/categories/id` again, customizations won't have category_ids as per the contract document, right?

**Comment by Jagannath-wits** [comment] 2024-03-22 12:56
1. 

> @Jagannath-wits as per the contract doc customizations, short_desc and long_desc are not present
> 
> ```
>               "descriptor":
>               {
>                 "name":"New Hand Tossed"
>               },
> ```

i have mentioned the long and short descriptions for items and not customization

**Comment by venkat77777** [comment] 2024-03-22 12:58
@Jagannath-wits `Item_id: 0ae6b110-c407-11ee-8a4f-03de6b9a1857:MxSDrFVEJz5n7KenwtGygL should have custom_group_id one of the ids passed in categories bpp/providers[2]` it did have the custom_group id in the tags, right?
```{
                  "code": "custom_group",
                  "list": [
                    {
                      "code": "id",
                      "value": "1_CG"
                    }
                  ]
                },```

**Comment by Jagannath-wits** [comment] 2024-03-22 12:58
> @Jagannath-wits as per the contract minimum value is string only with two decimal places
> 
> ```
>               "list":
>               [
>                 {
>                   "code":"min_value",
>                   "value":"300.00"
>                 }
>               ]
>             },
> ```

yes it will be string

**Comment by venkat77777** [comment] 2024-03-22 13:00
@Jagannath-wits `Value in catalog/items3/tags3/config/list/ should be one of the catalog/category/ids` i'm passing category group ids only, right?
```{
                  "code": "custom_group",
                  "list": [
                    {
                      "code": "id",
                      "value": "1_CG"
                    }
                  ]
                },
                {
                  "code": "config",
                  "list": [
                    {
                      "code": "id",
                      "value": "1_CG"
                    },```

**Comment by venkat77777** [comment] 2024-03-22 13:01
@Jagannath-wits `Location ID: Location_id should be same for the item d517b490-0aab-11ee-8ac0-3b78afefe16f:MxBP2YIbdEmMcVM64qEvN1:DC as in on_search
Location ID: Location_id should be same for the item 7f99ede0-da2a-11ee-9f48-0f9239d4a820:MxBP2YIbdEmMcVM64qEvN1:C:d517b490-0aab-11ee-8ac0-3b78afefe16f as in on_search`

Above are customizations and won't have matching location_ids

**Comment by venkat77777** [comment] 2024-03-22 13:06
@Jagannath-wits i have checked on_select & on_init of flow 2, i don't see any mismatch of quote, i just see order of items changed

`Quantity Error: Extra attribute Quantity provided in quote object i.e not supposed to be provided after on_select so invalid quote object`

**Comment by venkat77777** [comment] 2024-03-22 13:10
@Jagannath-wits as per the contract doc, we added following in on_confirm
``` "@ondc/org/settlement_basis":"delivery",
        "@ondc/org/settlement_window":"P1D",
        "@ondc/org/withholding_amount":"10.00",
```
other than this, nothing else changed

**Comment by Jagannath-wits** [comment] 2024-03-22 13:17
> @Jagannath-wits i have checked on_select & on_init of flow 2, i don't see any mismatch of quote, i just see order of items changed
> 
> `Quantity Error: Extra attribute Quantity provided in quote object i.e not supposed to be provided after on_select so invalid quote object`

@venkat77777 you have provided quantity in quote.breakup which is not required after on_select 
so its not a mismatch but invalid

**Comment by Jagannath-wits** [comment] 2024-03-22 18:44
> @Jagannath-wits as per the contract doc, we added following in on_confirm
> 
> ```
>         "@ondc/org/settlement_window":"P1D",
>         "@ondc/org/withholding_amount":"10.00",
> ```
> 
> other than this, nothing else changed

Yes this is correct

**Comment by venkat77777** [comment] 2024-03-23 03:14
@Jagannath-wits `Item4id Parent Item ID: /message/order/items/parent_item_id cannot be duplicate if item/id is same`  this is ondc buyer app issue and i believe they've fixed it now

**Comment by venkat77777** [comment] 2024-03-23 03:15
@Jagannath-wits `On Status Picked
Transaction ID Consistency: Transaction Id should be same from /select onwards` transaction id is same

**Comment by venkat77777** [comment] 2024-03-23 03:16
@Jagannath-wits `Order ID Mismatch: Order id in /confirm and /on_status_picked do not match` order is also same, not sure from where you see different order id

**Comment by venkat77777** [comment] 2024-03-23 03:18
@Jagannath-wits ```On Status Picked
Transaction ID Consistency: Transaction Id should be same from /select onwards
Order ID Mismatch: Order id in /confirm and /on_status_picked do not match
Timestamp Mismatch: Created At timestamp for /on_status_picked should be equal to context timestamp at confirm
Timestamp Order: Timestamp for /on_confirm api cannot be greater than or equal to /on_status_picked api```

All these errors are not exist

**Comment by venkat77777** [comment] 2024-03-23 03:19
@Jagannath-wits ```On Status Out for Delivery
Transaction ID Consistency: Transaction Id should be same from /select onwards
Order ID Mismatch: Order id in /confirm and /on_status_out-for-delivery do not match
Timestamp Mismatch: Created At timestamp for /on_status_out-for-delivery should be equal to context timestamp at confirm
Timestamp Order: Timestamp for /on_confirm api cannot be greater than or equal to /on_status_out-for-delivery api
```
Again all these errors do not exist in the logs

**Comment by venkat77777** [comment] 2024-03-23 03:20
@Jagannath-wits ```**Schema Error **: /message/order/fulfillments/1/end must have required property 'location'
**Schema Error **: /message/order/fulfillments/1/end must have required property 'person'
**Schema Error **: /message/order/fulfillments/1/end must have required property 'contact'
**Schema Error **: /message/order/fulfillments/1/end/time must have required property 'range'```

Cancel fulfillment will not have these values as per the contract doc

**Comment by venkat77777** [comment] 2024-03-23 03:25
@Jagannath-wits 
```**Schema Error **: /message/order/fulfillments/1/tags/0/list/4/code must be equal to one of the allowed values (reason_id, initiated_by, fulfillment_state, updated_at, retry_count, rto_id, id, currency, value, type)
**Schema Error **: /message/order/fulfillments/1/tags/1/list/4/code must be equal to one of the allowed values (reason_id, initiated_by, fulfillment_state, updated_at, retry_count, rto_id, id, currency, value, type)
**Schema Error **: /message/order/fulfillments/1/tags/2/list/4/code must be equal to one of the allowed values (reason_id, initiated_by, fulfillment_state, updated_at, retry_count, rto_id, id, currency, value, type)
**Schema Error **: /message/order/fulfillments/1/tags/3/list/4/code must be equal to one of the allowed values (reason_id, initiated_by, fulfillment_state, updated_at, retry_count, rto_id, id, currency, value, type)
**Schema Error **: /message/order/fulfillments/1/tags/4/list/4/code must be equal to one of the allowed values (reason_id, initiated_by, fulfillment_state, updated_at, retry_count, rto_id, id, currency, value, type)
**Schema Error **: /message/order/fulfillments/1/tags/5/list/4/code must be equal to one of the allowed values (reason_id, initiated_by, fulfillment_state, updated_at, retry_count, rto_id, id, currency, value, type)```

As per the contract doc, these values must be present in delivery fulfillment not in cancel fulfillment

**Comment by venkat77777** [comment] 2024-03-23 03:36
> > @Jagannath-wits i have checked on_select & on_init of flow 2, i don't see any mismatch of quote, i just see order of items changed
> > `Quantity Error: Extra attribute Quantity provided in quote object i.e not supposed to be provided after on_select so invalid quote object`
> 
> @venkat77777 you have provided quantity in quote.breakup which is not required after on_select so its not a mismatch but invalid

``` "quote":
      {
        "price":
        {
          "currency":"INR",
          "value":"1955.65"
        },
        "breakup":
        [
          {
            "@ondc/org/item_id":"I1",
            "@ondc/org/item_quantity":
            {
              "count":1
            },
            "title":"Farm House Pizza",
            "@ondc/org/title_type":"item",
            "price":
            {
              "currency":"INR",
              "value":"269.00"
            },
``` quantity is there in the contract doc, above is in on_init in api contract doc

**Comment by venkat77777** [comment] 2024-03-23 03:39
@Jagannath-wits `Flow 6-b and 6-c
Please provide labelled flows for reverse QC (6-b) and liquidation (6-c) with all on_update calls as on_update approved is missing for 6-b`

We don't have 6-b implemented, only 6-c is applicable for us and thus implemented the same. And earlier(RET10 submission) we were asked to combine 6-a and 6-c and apply it for single order

**Comment by venkat77777** [comment] 2024-03-23 04:11
@Jagannath-wits @sandeepshahi @BLR-0118 from the above feedback given, only the below ones are actual errors and will be fixing them. Please confirm

```Flow 1

Search Full Catalog Refresh
Schema Error 0: /context/action must be equal to constant (search)
Action Error: context.action should be search

On Search Full Catalog Refresh
**Schema Error **: /message/catalog/bpp~1providers/0/@ondc~1org~1fssai_license_no must NOT have fewer than 14 characters
**Schema Error **: /message/catalog/bpp~1providers/0/categories/1 must have required property 'parent_category_id'
Schema Error: /message/catalog/bpp~1providers/0/items/0/category_ids/0 format of category_ids must be followed as per API contract

Search Incremental Refresh
**Schema Error **: /context/action must be equal to constant (search)
Action Error: context.action should be search

On Search Incremental Refresh
**Schema Error **: /message/catalog/bpp~1providers/0/items/0/category_ids/0 must match pattern "^[a-zA-Z0-9]{1,12}:[a-zA-Z0-9]{1,12}$"
**Schema Error **: /message/catalog/bpp~1providers/0/items/1/category_ids/0 must match pattern "^[a-zA-Z0-9]{1,12}:[a-zA-Z0-9]{1,12}$"

On Cancel Errors
Invalid Quote Trail Prices: Quote_trail price and item quote price sum for on_cancel should be equal to the price as in on_confirm```

**Comment by Jagannath-wits** [comment] 2024-03-23 04:58
> > > @Jagannath-wits i have checked on_select & on_init of flow 2, i don't see any mismatch of quote, i just see order of items changed
> > > `Quantity Error: Extra attribute Quantity provided in quote object i.e not supposed to be provided after on_select so invalid quote object`
> > 
> > 
> > @venkat77777 you have provided quantity in quote.breakup which is not required after on_select so its not a mismatch but invalid
> 
> ```
>       {
>         "price":
>         {
>           "currency":"INR",
>           "value":"1955.65"
>         },
>         "breakup":
>         [
>           {
>             "@ondc/org/item_id":"I1",
>             "@ondc/org/item_quantity":
>             {
>               "count":1
>             },
>             "title":"Farm House Pizza",
>             "@ondc/org/title_type":"item",
>             "price":
>             {
>               "currency":"INR",
>               "value":"269.00"
>             },
> ``` quantity is there in the contract doc, above is in on_init in api contract doc
> ```

"breakup":
        [
          {
            "@ondc/org/item_id":"I1",
            "@ondc/org/item_quantity":
            {
              "count":1
            },
            "title":"Farm House Pizza",
            "@ondc/org/title_type":"item",
            "price":
            {
              "currency":"INR",
              "value":"269.00"
            },
            "item":
            {
              "parent_item_id":"DI1",
              "price":
              {
                "currency":"INR",
                "value":"269.00"
              },

As given in contract quantity object is not there in breakup.item in confirm and on_confirm

**Comment by Jagannath-wits** [comment] 2024-03-23 05:06
> @Jagannath-wits `On Status Picked Transaction ID Consistency: Transaction Id should be same from /select onwards` transaction id is same

this is in flow 6

**Comment by venkat77777** [comment] 2024-03-23 05:07
@Jagannath-wits are you talking about this?
```"quantity": {
                "available": {
                  "count": "99"
                },
                "maximum": {
                  "count": "99"
                }
              },```

**Comment by venkat77777** [comment] 2024-03-23 05:09
> > @Jagannath-wits `On Status Picked Transaction ID Consistency: Transaction Id should be same from /select onwards` transaction id is same
> 
> this is in flow 6

![Screenshot from 2024-03-23 10-38-37](https://github.com/ONDC-Official/v1.2.0-logs/assets/39147500/a69f83c8-35e3-40b3-9b83-b742f4f1cc24)
flow 6 has same transaction id across all apis

**Comment by Jagannath-wits** [comment] 2024-03-23 05:19
> > > @Jagannath-wits `On Status Picked Transaction ID Consistency: Transaction Id should be same from /select onwards` transaction id is same
> > 
> > 
> > this is in flow 6
> 
> ![Screenshot from 2024-03-23 10-38-37](https://private-user-images.githubusercontent.com/39147500/316218559-a69f83c8-35e3-40b3-9b83-b742f4f1cc24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExNzEzODAsIm5iZiI6MTcxMTE3MTA4MCwicGF0aCI6Ii8zOTE0NzUwMC8zMTYyMTg1NTktYTY5ZjgzYzgtMzVlMy00MGIzLTliODMtYjc0MmY0ZjFjYzI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDA1MTgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNGFkOWRkNTFhZjExMTQzOGQ0Mjc5NThjMWZjYTA0N2QyNTE3MzNiOGNhOWYwYTZhYWRiNmVjNzlmODU5ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jeT90yOSopAZB9PcO5HECOBpQ0a3uTKxM1YsaEfho2U) flow 6 has same transaction id across all apis

ok this is correct

**Comment by Jagannath-wits** [comment] 2024-03-23 05:19
> @Jagannath-wits are you talking about this?
> 
> ```
>                 "available": {
>                   "count": "99"
>                 },
>                 "maximum": {
>                   "count": "99"
>                 }
>               },```
> ```

yes

**Comment by venkat77777** [comment] 2024-03-23 05:36
> @Jagannath-wits
> 
> ```
> **Schema Error **: /message/order/fulfillments/1/tags/1/list/4/code must be equal to one of the allowed values (reason_id, initiated_by, fulfillment_state, updated_at, retry_count, rto_id, id, currency, value, type)
> **Schema Error **: /message/order/fulfillments/1/tags/2/list/4/code must be equal to one of the allowed values (reason_id, initiated_by, fulfillment_state, updated_at, retry_count, rto_id, id, currency, value, type)
> **Schema Error **: /message/order/fulfillments/1/tags/3/list/4/code must be equal to one of the allowed values (reason_id, initiated_by, fulfillment_state, updated_at, retry_count, rto_id, id, currency, value, type)
> **Schema Error **: /message/order/fulfillments/1/tags/4/list/4/code must be equal to one of the allowed values (reason_id, initiated_by, fulfillment_state, updated_at, retry_count, rto_id, id, currency, value, type)
> **Schema Error **: /message/order/fulfillments/1/tags/5/list/4/code must be equal to one of the allowed values (reason_id, initiated_by, fulfillment_state, updated_at, retry_count, rto_id, id, currency, value, type)```
> 
> As per the contract doc, these values must be present in delivery fulfillment not in cancel fulfillment
> ```

@Jagannath-wits please confirm this too

**Comment by venkat77777** [comment] 2024-03-23 05:37
> @Jagannath-wits `**Schema Error **: /message/order/fulfillments/1/end must have required property 'location' **Schema Error **: /message/order/fulfillments/1/end must have required property 'person' **Schema Error **: /message/order/fulfillments/1/end must have required property 'contact' **Schema Error **: /message/order/fulfillments/1/end/time must have required property 'range'`
> 
> Cancel fulfillment will not have these values as per the contract doc

@Jagannath-wits confirm this too

**Comment by Jagannath-wits** [comment] 2024-03-23 05:52
> > @Jagannath-wits
> > ```
> > **Schema Error **: /message/order/fulfillments/1/tags/1/list/4/code must be equal to one of the allowed values (reason_id, initiated_by, fulfillment_state, updated_at, retry_count, rto_id, id, currency, value, type)
> > **Schema Error **: /message/order/fulfillments/1/tags/2/list/4/code must be equal to one of the allowed values (reason_id, initiated_by, fulfillment_state, updated_at, retry_count, rto_id, id, currency, value, type)
> > **Schema Error **: /message/order/fulfillments/1/tags/3/list/4/code must be equal to one of the allowed values (reason_id, initiated_by, fulfillment_state, updated_at, retry_count, rto_id, id, currency, value, type)
> > **Schema Error **: /message/order/fulfillments/1/tags/4/list/4/code must be equal to one of the allowed values (reason_id, initiated_by, fulfillment_state, updated_at, retry_count, rto_id, id, currency, value, type)
> > **Schema Error **: /message/order/fulfillments/1/tags/5/list/4/code must be equal to one of the allowed values (reason_id, initiated_by, fulfillment_state, updated_at, retry_count, rto_id, id, currency, value, type)```
> > 
> > As per the contract doc, these values must be present in delivery fulfillment not in cancel fulfillment
> > ```
> 
> @Jagannath-wits please confirm this too

this is false error

**Comment by Jagannath-wits** [comment] 2024-03-23 05:55
> * person

this is false error

**Comment by Jagannath-wits** [comment] 2024-03-23 05:55
> > @Jagannath-wits `**Schema Error **: /message/order/fulfillments/1/end must have required property 'location' **Schema Error **: /message/order/fulfillments/1/end must have required property 'person' **Schema Error **: /message/order/fulfillments/1/end must have required property 'contact' **Schema Error **: /message/order/fulfillments/1/end/time must have required property 'range'`
> > Cancel fulfillment will not have these values as per the contract doc
> 
> @Jagannath-wits confirm this too

this is false error

**Comment by venkat77777** [comment] 2024-03-23 09:12
@Jagannath-wits please check this PR https://github.com/ONDC-Official/v1.2.0-logs/pull/1188, all issues that are applicable from above list are included and added item level tax(5% govt gst) changes too

**Comment by BLR-0118** [comment] 2024-04-01 06:50
closing, duplicate of #985

**Closed by BLR-0118** 2024-04-01 06:50 UTC
