### ISSUE TITLE
GrowthFalcons (RET11) — compliance checks

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/v1.2.0-logs#351] opened 2023-12-24 13:28 UTC
## Flow 1

**/search (incremental)**

- context/city must be "\*" in incremental search

**/on_search (incremental)**

- context/domain must be ONDC RET namespace

**/on_search (incremental)**

- complete provider details need not be provided in incremental refresh; check the contract for incremental schema

**/on_search**

- /message/catalog/bpp/providers/ must have required property 'fulfillments', '@ondc/org/fssai_license_no', 'ttl', 'locations' in the full catalog; BNP might throw schema issue
- display sequence of multiple items in a particular custom menu can't be same; eg: items- "a7de87f6-b895-46ee-a69c-54e1d0be377f" and "450937c6-d5ee-4287-9858-32d5547785d2" have sequence = 1 in custom menu: "3550991"

## Flow 2

**/on_select**

- Delivery TAT may be provided in a compact format; "PT1H30M"/ "PT90M" instead of "P0DT1H30M0S"

**/on_confirm**

- estimated delivery time range (/fulfillments/end/time/range) is invalid; can't take 24 hours for an "Immediate Delivery" fulfillment

**/status**

- No /on_status callback response in the logs

**/on_status**

- /message/order/fulfillments/0 must have required property '@ondc/org/TAT'
- context/message_id should be unique for each unsolicited call
- available and maximum count in quote/breakup/item/quantity should be in string format
- context/timestamp can't be same for subsequent unsolicited calls (pending, packed, delivered)
- Order state must be "In-progress" when fulfillment state is "Packed"
- context/timestamp and order/updated_at timestamps are not captured correctly in "Order-delivered" state

**/on_track**

- time/timestamp and updated_at timestamp in /tracking/location/ should be <= context/timestamp

## Flow 5

**/on_cancel**

- RTO flow is missing as per the test case scenario
- quote_trail is missing in /fulfillments

@SandeepGF

**Comment by SandeepGF** [comment] 2023-12-28 07:38
@bluecypher @BLR-0118  need clarification on Flow 5:
1. If the item is non-returnable and non-cancelable Do we need to initiate the RTO flow?
2. Suppose the entire order is canceled by the merchant, is /on_cancel enough?
3. If Order was Cancelled by the logistics and the issue is at Buyer's end (Address is incorrect, location is away 5km from the actual location) in such cases if the seller app is not ready to refund Do I need to add the quote trail in the fulfillment?

**Comment by sahil-ondc** [comment] 2024-01-03 10:42
## Flow 1

**on_search_full_catalog_refresh**

- /message/catalog/bpp/providers/0 must have required property 'fulfillments'
- /message/catalog/bpp/providers/0 must have required property '@ondc/org/fssai_license_no'
- /message/catalog/bpp/providers/0 must have required property 'ttl'
- /message/catalog/bpp/providers/0 must have required property 'locations'
- /message/catalog/bpp/providers/0 must have required property 'items'
- /message/catalog/bpp/providers/0 must have required property 'tags'
- /message/catalog/bpp/providers/id should not match /message/catalog/bpp/providers/locations/id

**on_search_inc_catalog_refresh**

- /message/catalog/bpp/providers/0 should not have property '@ondc/org/fssai_license_no'

## Flow 2

**on_init**

- /message/order should not have property 'provider_location'
- /message/order/quote/breakup should be as per the api contract
  `https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit`

**on_track**

- /message/tracking should not have empty array 'tags'


## Note 

Flow 4 and Flow 6 Need to be submitted

@SandeepGF

**Comment by SandeepGF** [comment] 2024-01-04 04:30
@BLR-0118 
1. If we do not have returnable and Cancelable products Do we need to submit the logs for Flow 4 and Flow 6 ?
2. Since we are in prod with v1.1.0. do we need to remove provider_location?

@VidyaGF

**Comment by BLR-0118** [comment] 2024-01-06 12:53
1. Flow 4 & 6 - yes;
2. Yes

**Comment by BLR-0118** [comment] 2024-01-06 12:54
@SandeepGF

**Comment by BLR-0118** [comment] 2024-01-15 08:13
Flow 1
====
1. Full catalog refresh:
- multiple customization groups for an item needs to be done as doc [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.jgj38hso0lnk);
- customization group configuration at item level may be added if it overrides what's specified at provider.categories level; any reason why same config is being repeated at item level?
- request to add np_type;
 
2. Incremental refresh:
- is there support for incremental push? (all SNPs need to support both pull & push)
- what has changed for this item (2a5d31a6-5250-4d72-a556-177da141b305, a1a22252-31c5-4ded-859a-ea783f4b294a-VAR-1253694478) that it's being sent in incremental refresh - if it's ranking in the custom menu, you can do in full pull itself;

Flow 2
====
1. /on_confirm:
- request to add provider_tax_number, fulfillment TAT (already in /on_status);

2. /on_track:
- to optimize processing of /track & /on_track, pls set the following attributes in fulfillment as doc [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.1niyckvc1hd):
- "routing"."type":"P2P", "tracking"."gps_enabled":"yes";

Flow 4
====
1. /on_cancel:
- quote.breakup for item is wrong (qty should become 0 as it's been assigned to 0 (for F1 in items[]), hence total price = 0 (note that total price = unit price * qty);

Flow 5
====
1. /on_cancel (rto initiated):
- quote_trail for item should be -538 since that's being refunded (implicit since quote.breakup shows 0 for item);
- quote.breakup is wrong (same as flow 4);
- can we have precancel_state (as in /on_cancel for flow4)?

**Comment by BLR-0118** [comment] 2024-01-15 08:13
@SandeepGF

**Comment by BLR-0118** [comment] 2024-01-15 08:13
@SandeepGF - pls fix all the above but only resubmit logs for flow 4 & 5

**Comment by BLR-0118** [comment] 2024-01-22 18:01
@SandeepGF - log cleared for v1.2.0

**Closed by BLR-0118** 2024-01-22 18:01 UTC
