### ISSUE TITLE
MP2  (LSP-IGM) - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#447] opened 2024-01-04 11:12 UTC
Issue :

- The 'updated_at' of message/issue/issue_action/complainant_actions/index[0]/updated_at should be the same or greater than as 'message/issue/update_at' in issue , and can u pls explain why difference in the timesatamp is that much .

@Poornima-Aithal

**Comment by mherle** [comment] 2024-01-04 16:15
Hi @RupalSingla 

Since the issue is only from the LBNP, should we consider this as logs approved for MP2 LSP ?

Cc: @BLR-0118 @Rishabh-ondc ?

**Comment by Rishabh-ondc** [comment] 2024-01-08 12:28
Logs cleared

@mherle

**Comment by mherle** [comment] 2024-01-08 12:29
Thanks @Rishabh-ondc . Appreciate this

**Comment by mherle** [comment] 2024-01-09 12:26
@bluecypher pls do close this issue, as the logs are cleared for LSP

**Comment by mherle** [comment] 2024-02-14 05:33
@bluecypher Can you pls mark this issue as closed ?

**Comment by mherle** [comment] 2024-04-26 10:55
@abhinavv245 Pls close this issue

**Closed** 2024-05-13 10:37 UTC
