### ISSUE TITLE
Channelier (Seller App - RET10) - Compliance check

### ISSUE THREAD

**Issue by nishthamongaondc** [ONDC-Official/v1.2.0-logs#879] opened 2024-02-20 08:07 UTC
### on_search_full_catalog_refresh
- /message/catalog/bpp~1providers/0/items/0/quantity/unitized/measure/unit must be equal to one of the allowed values (unit,dozen,gram,kilogram,tonne,litre,millilitre)
- /message/catalog/bpp~1providers/0/items/0/quantity/available/count available/count must be equal to one of the allowed values i.e 99 if in stock or 0 if not in stock
- /message/catalog/bpp~1providers/0/items/0/category_id Invalid catrgory ID found for item for on_search
- In ONDC:RET10 @ondc/org/statutory_reqs_prepackaged_food imported_product_country_of_origin is not required.
### on_search_inc_refresh
- provider id: CU19 in bpp/providers didn't matched for providers id of /on_search_full_catalog_refresh
### on_select
- City code mismatch in /search and /on_select
- provider.id mismatches in /on_search and /on_select

@itsRajatkumar

**Comment by nishthamongaondc** [comment] 2024-02-26 12:32
## Flow 2

### on_status_pending
- /message/order/id Should be alphanumeric upto 32 letters max

### on_status_packed
- /message/order/id Should be alphanumeric upto 32 letters max
- City code mismatch in /search and /on_status
- pickup timestamp should match context/timestamp and can't be future dated
- order/updated_at timestamp can't be less than the pickup time

### on_status_picked
- /message/order/id Should be alphanumeric upto 32 letters max

### on_status_out_for_delivery
- /message/order/id Should be alphanumeric upto 32 letters max

### on_status_delivered
- /message/order/id Should be alphanumeric upto 32 letters max

@itsRajatkumar

**Comment by itsRajatkumar** [comment] 2024-02-26 13:23
@nishthamongaondc The issue in all status calls for orders ID because of buyer app. 
Order Ids were generated by the buyer app and we are using buyer reference app 1.2. and it is sending IDs like `2024-02-21-263465`


- /message/order/id Should be alphanumeric upto 32 letters max

**Comment by bluecypher** [comment] 2024-02-27 06:52
@itsRajatkumar, please ignore the counterparty app related issues

**Comment by itsRajatkumar** [comment] 2024-03-05 07:25
@bluecypher @nishthamongaondc Any updates over the latest logs submissions it was raised 5 days ago. #955

**Comment by NishthaMonga** [comment] 2024-03-06 12:37
## Flow 2
### on_select
- item.quantity.available.count should be either 99 (inventory available) or 0 (out-of-stock)

### on_status_delivered
- order/updated_at timestamp can't be less than the delivery time

## Flow 3
### on_confirm
- Tags should have same and valid gst_number as passed in /confirm

## Flow 4
### on_select
- provider.id mismatches in /on_search and /on_select

### on_confirm
- Provider Id mismatches in /on_search and /on_confirm

### on_cancel
- /message/order/fulfillments/0 must have required property 'tags'
- /message/order/fulfillments/0/state/descriptor/code must be equal to one of the allowed values (Cancelled)
- precancel_state not found in fulfillments for on_cancel

## Flow 5
### on_cancel
- /message/order/fulfillments/0/state/descriptor/code must be equal to one of the allowed values (Cancelled,RTO-Initiated,RTO-Delivered,RTO-Disposed)


@itsRajatkumar

**Comment by NishthaMonga** [comment] 2024-03-15 11:08
## Flow 2
### on_confirm
- mandatory fields like np_type,provider_tax_number,etc  missing in message/order/tags/bpp_terms for ON_CONFIRM

## Flow 3
### on_select_out_of_stock
- item.quantity.maximum.count cannont be greater than 0 if item.quantity.available.count is 0

### on_confirm
- mandatory fields like np_type,provider_tax_number,etc  missing in message/order/tags/bpp_terms for ON_CONFIRM

## Flow 5
### on_cancel
- quote_trail price and item quote price sum for on_cancel should be equal to the price as in on_confirm
- Pre Cancel is mandatory for on_cancel

## Flow 6A
### on_update
- Price mismatch for  [CU19I0] provided in quote object '[416]' /on_cancel

@itsRajatkumar

**Comment by ravinderTechpvec18** [comment] 2024-03-15 12:25
@NishthaMonga  @sandeepshahi 
We ahve following queries regarding todays logs comments for RET:10
1. Flow 5 - comment 1 - quote trail price in on_cancel is Rs -208 and in on_confirm its Rs.208. According to comment they are differ, can you pls mention the exact difference.
2. Flow 6 - 4 quantities of Item CU19I0 has been ordered, 2 has been partially cancelled, so in quote trail its Rs -208 and in quote object its 208 remaining (price for one CU19I0 is 108). According to comment they differ in value can u pls comment exact difference

**Comment by BLR-0118** [comment] 2024-03-24 09:18
Flow 1
====
1. /on_search (full catalog):
- keys used in bpp_terms are invalid (check valid keys from [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.yr8id0fwawkv));
- bpp/fulfillments.id and bpp/providers.fulfillments.id must match;
- circle.radius.value of 3000km ?? (radius of earth itself is about 6000km, so does this mean, your serviceability is for half of the earth?);
- pls remove formatting from manufacturer_or_packer_address;
- item CU19I0 (& others) show "80 g" in name but 120.8 in net qty quantity.unitized.measure?

2. /on_search (incremental):
- are you not supporting incremental push?

Flow 2
====
1. /on_select:
- what's the logic for quoting TAT of P7DT48H (i.e. 9 days) for delivery between 110077 & 110070?

2. /on_init:
- remove provider_location;

3. /on_confirm:
- pls use same address keys, for fulfillment.start, as for fulfillment.end;
- fulfillment pickup slot is 20th to 22nd & delivery slot is 20th to 29th; can we have some realistic values here (also see comment in /on_select above);
- provider_tax_number required here;

4. /on_status APIs:
- seller invoice should be added at order pickup;
- pls send routing.type to indicate hyperlocal (P2P) or intercity shipment (P2H2P);

Flow 3
====
1. /on_select_out_of_stock:
- error number should also be with escaped double quotes;

Flow 4
====
1. /on_cancel:
- why is delivery charge not being refunded even though fulfillment is in Pending state?

Flow 5
====
1. /on_cancel:
- cancel_request.initiated_by should have bpp_id;

**Comment by BLR-0118** [comment] 2024-03-24 11:19
Flow 6
====
1. /on_update_partial_cancel:
- cancelled_by should be same as bpp_id;

**Comment by BLR-0118** [comment] 2024-03-24 11:20
@ravinderTechpvec18 - pls fix all issues & resubmit logs for flow 2 only (to verify most fixes)

**Comment by ravinderTechpvec18** [comment] 2024-03-24 23:56
Flow 1 /on_search in incremental, we are supporting incremental catalog
refresh (1-time)

**Comment by BLR-0118** [comment] 2024-03-25 05:38
@ravinderTechpvec18 - you need to support incremental push as defined in contract [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.35k5gqc5go50);

**Comment by ravinderTechpvec18** [comment] 2024-03-25 06:10
we are supporting incremental catalog push, pushing changes 1 time to the
buyer NP, with paginated response per seller, as in retail contract 1.2

**Comment by BLR-0118** [comment] 2024-03-25 06:15
@ravinderTechpvec18 - what I meant is:
- async push updates to buyer app at a particular frequency (10-30 mins), as & when changes happen;
- what you seem to be supporting now is responding to an incremental pull request, which buyer apps may not use frequently;
- check the link I shared above for diff between incremental pull & push;

**Comment by ravinderTechpvec18** [comment] 2024-03-25 08:13
we are currently in process of developing incremental push, feature will be
up for testing in preproduction before thrusday

**Comment by BLR-0118** [comment] 2024-03-26 07:22
Flow 2
====
1. /on_confirm:
- since TAT is 4 hrs & pickup slot between 02:04 & 04:04, shouldn't end slot be between 06:04 & 08:04 (in which case max TAT could be 6 hrs)?

2. /track & /on_track:
- to optimize processing between buyer & seller apps, can you pls update the tracking status (gps_enabled, url_enabled+url) in /on_status when tracking has been enabled? This way, buyer apps can call /track for latest gps coords & for url, they can fetch from /on_status itself;
- pls have the complete payload for /on_track as per contract;

**Comment by BLR-0118** [comment] 2024-03-26 07:24
@ravinderTechpvec18:
- I hope other issues raised above for flows 1/3/4/5/6 have been fixed? If so, pls make a note here for each issue raised;
- pls fix the above issues raised for flow 2 & make a note here for each issue raised;
- I'll wait for your note here before clearing logs, pls don't resubmit logs;

**Comment by ravinderTechpvec18** [comment] 2024-03-26 08:20
Flow 1
/on_search (full catalog):
Issue 1: keys used in bpp_terms are invalid (check valid keys from here) ;
Issue 1 Resolution: there was '-' instead of '_' for one key and spelling for one key is wrong. All the attributes names are fixed
Issue 2: bpp/fulfillments.id and bpp/providers.fulfillments.id must match;
Issue 2 resolution: This has been fixed now for all search request bpp/fulfillments.id and bpp/providers.fulfillments.id matches.
Issue 3: circle.radius.value of 3000km ?? (radius of earth itself is about 6000km, so does this mean, your serviceability is for half of the earth?);
Issue 3 Resolution: we have put down the vaue as 500 kms for all pan india selling products
 Issue 4: pls remove formatting from manufacturer_or_packer_address;
issue 4 Resolution: we have removed the formatting now whole address of the manufacturer will be communicated in one single string
 Issue 5: item CU19I0 (& others) show "80 g" in name but 120.8 in net qty quantity.unitized.measure?
Issue 5 resolution: rectified
Flow 2
/on_select:
issue 1: what's the logic for quoting TAT of P7DT48H (i.e. 9 days) for delivery between 110077 & 110070?
Issue 1 Resolution: rectified and reduced to 2 hours
/on_init:
Issue 2: remove provider_location;
Issue 2 Resolution: provider_location has been removed from on_init payload
/on_confirm:
Issue 3: pls use same address keys, for fulfillment.start, as for fulfillment.end;
Issue 3 resolution: fulfillment.start and fulfillment.end addresses now have same attributes in name and count
Issue 4: fulfillment pickup slot is 20th to 22nd & delivery slot is 20th to 29th; can we have some realistic values here (also see comment in /on_select above);
Issue 5 resolution: rectified
Issue 6: provider_tax_number required here;
Issue 6 Resolution: provider_tax_number has been added to tags for bpp_terms
/on_status APIs:
Issue 7: seller invoice should be added at order pickup;
Issue 7 resolution: seller invoice url has been added
Issue 8: pls send routing.type to indicate hyperlocal (P2P) or intercity shipment (P2H2P);
Issue 8 Resolution: routing.type has been added in fulfillment tags
Flow 3
/on_select_out_of_stock:
Issue 1: error number should also be with escaped double quotes;
Issue 1 Resolution: now its coming like "[{\"item_id\":\"CU254I0\",\"error\":\"40002\"}]"
Flow 4
/on_cancel:
Issue 1: why is delivery charge not being refunded even though fulfillment is in Pending 
state?
Issue 1 Resolution: Rectified, now in cancallation fulfillment quote trail we are also sending quote trail for delivery charges and in quote delivery charges will be zero
Flow 5
/on_cancel:
Issue 1: cancel_request.initiated_by should have bpp_id;
Issue 1 Resolution: rectified

Dated: 26/03/2024
Flow 2
/on_confirm:
Issue 1: since TAT is 4 hrs & pickup slot between 02:04 & 04:04, shouldn't end slot be between 06:04 & 08:04 (in which case max TAT could be 6 hrs)?
Issue 1 Resolution: We were actually calculating the time slots like you have suggested, but while logs verification for version 1.1 last july-august, we were specifically told to calculate end time slots to start with time stamp of start.time.range.start + 5 secs. So we have acted on the suggestion.
/track & /on_track:
Issue 2: to optimize processing between buyer & seller apps, can you pls update the tracking status (gps_enabled, url_enabled+url) in /on_status when tracking has been enabled? This way, buyer apps can call /track for latest gps coords & for url, they can fetch from /on_status itself;

Issue 2 resolution: Tags are missing from the payload as they are marked as optional, But if they are mandatory then we can integrate them also
pls have the complete payload for /on_track as per contract;

**Comment by ravinderTechpvec18** [comment] 2024-03-26 08:20
Flow 1
/on_search (full catalog):
Issue 1: keys used in bpp_terms are invalid (check valid keys from here) ;
Issue 1 Resolution: there was '-' instead of '_' for one key and spelling
for one key is wrong. All the attributes names are fixed
Issue 2: bpp/fulfillments.id and bpp/providers.fulfillments.id must match;
Issue 2 resolution: This has been fixed now for all search request bpp/
fulfillments.id and bpp/providers.fulfillments.id matches.
Issue 3: circle.radius.value of 3000km ?? (radius of earth itself is about
6000km, so does this mean, your serviceability is for half of the earth?);
Issue 3 Resolution: we have put down the vaue as 500 kms for all pan india
selling products
 Issue 4: pls remove formatting from manufacturer_or_packer_address;
issue 4 Resolution: we have removed the formatting now whole address of the
manufacturer will be communicated in one single string
 Issue 5: item CU19I0 (& others) show "80 g" in name but 120.8 in net qty
quantity.unitized.measure?
Issue 5 resolution: rectified
Flow 2
/on_select:
issue 1: what's the logic for quoting TAT of P7DT48H (i.e. 9 days) for
delivery between 110077 & 110070?
Issue 1 Resolution: rectified and reduced to 2 hours
/on_init:
Issue 2: remove provider_location;
Issue 2 Resolution: provider_location has been removed from on_init payload
/on_confirm:
Issue 3: pls use same address keys, for fulfillment.start, as for
fulfillment.end;
Issue 3 resolution: fulfillment.start and fulfillment.end addresses now
have same attributes in name and count
Issue 4: fulfillment pickup slot is 20th to 22nd & delivery slot is 20th to
29th; can we have some realistic values here (also see comment in
/on_select above);
Issue 5 resolution: rectified
Issue 6: provider_tax_number required here;
Issue 6 Resolution: provider_tax_number has been added to tags for bpp_terms
/on_status APIs:
Issue 7: seller invoice should be added at order pickup;
Issue 7 resolution: seller invoice url has been added
Issue 8: pls send routing.type to indicate hyperlocal (P2P) or intercity
shipment (P2H2P);
Issue 8 Resolution: routing.type has been added in fulfillment tags
Flow 3
/on_select_out_of_stock:
Issue 1: error number should also be with escaped double quotes;
Issue 1 Resolution: now its coming like
"[{\"item_id\":\"CU254I0\",\"error\":\"40002\"}]"
Flow 4
/on_cancel:
Issue 1: why is delivery charge not being refunded even though fulfillment
is in Pending
state?
Issue 1 Resolution: Rectified, now in cancallation fulfillment quote trail
we are also sending quote trail for delivery charges and in quote delivery
charges will be zero
Flow 5
/on_cancel:
Issue 1: cancel_request.initiated_by should have bpp_id;
Issue 1 Resolution: rectified

Dated: 26/03/2024
Flow 2
/on_confirm:
Issue 1: since TAT is 4 hrs & pickup slot between 02:04 & 04:04, shouldn't
end slot be between 06:04 & 08:04 (in which case max TAT could be 6 hrs)?
Issue 1 Resolution: We were actually calculating the time slots like you
have suggested, but while logs verification for version 1.1 last
july-august, we were specifically told to calculate end time slots to start
with time stamp of start.time.range.start + 5 secs. So we have acted on the
suggestion.
/track & /on_track:
Issue 2: to optimize processing between buyer & seller apps, can you pls
update the tracking status (gps_enabled, url_enabled+url) in /on_status
when tracking has been enabled? This way, buyer apps can call /track for
latest gps coords & for url, they can fetch from /on_status itself;

Issue 2 resolution: Tags are missing from the payload as they are marked as
optional, But if they are mandatory then we can integrate them also
pls have the complete payload for /on_track as per contract;

**Comment by BLR-0118** [comment] 2024-03-26 08:46
@ravinderTechpvec18 - pls also fix issues 1 & 2, added today, for flow 2 & make a note here;

**Comment by ravinderTechpvec18** [comment] 2024-03-26 08:54
sure sir

**Comment by itsRajatkumar** [comment] 2024-03-26 09:08
@BLR-0118 

for issue : **since TAT is 4 hrs & pickup slot between 02:04 & 04:04, shouldn't end slot be between 06:04 & 08:04 (in which case max TAT could be 6 hrs)?**


Comment: 
We have TAT of 4 Hours
2 Hour for the Max time_to_ship and 2 hour Delivery time 
in the confirm start.time.range is the time for time_to_ship so it is
02:04 to 04:04
after adding this the delivery TAT to time_to_ship it becomes 4 Hours 
so delivery Slot is from 02:04 to 06:04



for issue: **_to optimize processing between buyer & seller apps, can you pls
update the tracking status (gps_enabled, url_enabled+url) in /on_status
when tracking has been enabled? This way, buyer apps can call /track for
latest gps coords & for url, they can fetch from /on_status itself_**

**Resolution: Tags are missing from the payload as they are marked as optional**

**Comment by BLR-0118** [comment] 2024-03-26 09:40
@itsRajatkumar:
1. ok, if pickup slot is 02:04 to 04:04 & 2 hr delivery time, shouldn't delivery slot be 04:04 to 06:04?
2. request to pls add this to payload

**Comment by ravinderTechpvec18** [comment] 2024-03-26 10:06
sir we are working on it, will notify as soon as both points are ready

**Comment by itsRajatkumar** [comment] 2024-03-26 11:17
Hi @BLR-0118  
we have fixed the above-mentioned issues, 

## 1. TAT Pickup and delivery slot timing issues.
Resolution: 
The Total TAT is 4 Hours ( 2 hours Time to ship + 2 hours Delivery Time)
start range is 
```json
"range": {
    "start": "2024-03-26T10:54:00.595Z",
    "end": "2024-03-26T12:54:00.595Z"
}
```
end range is 
```json
"range": {
    "start": "2024-03-26T12:54:00.595Z",
    "end": "2024-03-26T14:54:00.595Z"
}
```

## 2. Tracking payload.
Resolution: Added the payload.

**Comment by BLR-0118** [comment] 2024-03-26 17:25
logs cleared for v1.2.0 (RET10)

**Closed by BLR-0118** 2024-03-26 17:25 UTC

**Comment by ravinderTechpvec18** [comment] 2024-03-27 01:10
Thanks for support sir
