### ISSUE TITLE
Ushop - compliance check

### ISSUE THREAD

**Issue by sahil-ondc** [ONDC-Official/v1.2.0-logs#53] opened 2023-10-20 10:01 UTC
### Flow 1

**search_inc_refresh**

- incorrect json

**on_search_full_catalog_refresh**

- /message/catalog/bpp~1providers/0/items/9/quantity/unitized/measure/unit must be equal to one of the allowed values (unit,dozen,gram,kilogram,tonne,litre,millilitre)
- category in serviceability construct should be one of the category ids bpp/providers[0]/items/category_id
- value should be a valid range of pincodes (code:"val") for type 11 (intercity) in /bpp/providers[0]/tags[0]

### Flow 2

**on_init**

- /message/order/billing must have required property 'tax_number'

**confirm**

- /message/order/payment must have required property '@ondc/org/settlement_basis'
- /message/order/payment must have required property '@ondc/org/settlement_window'
- /message/order/payment must have required property '@ondc/org/withholding_amount'

**on_confirm**

- store name /fulfillments[0]/start/location/descriptor/name can't change from 'on_search'
- payment object mismatches in /confirm & /on_confirm

### Common

- /message/order/billing/address must have required property 'building'
- /message/order/fulfillments/0/end/location/address must have required property 'building'

@ShippuYadav

**Comment by ShippuYadav** [comment] 2023-10-20 10:47
* value should be a valid range of pincodes (code:"val") for type 11 (intercity) in /bpp/providers[0]/tags[0]
Can you please explain where the issue is?
*/message/order/billing must have required property 'tax_number'
Its optional and should be coming from buyer app

*store name /fulfillments[0]/start/location/descriptor/name can't change from 'on_search'
It seems to be same

Please check this meanwhile Working on the rest of the mention point.
@sharmasahil0331 Please check

**Comment by ShippuYadav** [comment] 2023-10-21 14:48
@sharmasahil0331  Please check latest PR https://github.com/ONDC-Official/v1.2.0-logs/pull/55

**Comment by sharmasahil0331** [comment] 2023-10-23 08:55
**on_search (full catalog refresh)**

- reverse geocoding of /message/catalog/bpp/providers/locations/gps is different from address/area_code

**search (inc catalog refresh)**

- city must be "\*" in incremental pull

**on_search (inc catalog refresh)**

- /on_search/context/timestamp cannot be less than search/context/timestamp
- /message/catalog/bpp/providers/items should be sent only in case of any updates

**on_confirm**

- /message/order/fulfillments/0/tracking must be boolean

**on_status**

- /message/order/fulfillments/0 must have required property '@ondc/org/TAT'
- /message/order/fulfillments/0/end/time should have 'timestamp' only if state is 'Order-delivered'
- /message/order/payment/@ondc/org/settlement_details/0 must have required property 'settlement_timestamp'

**common**

- /message/order/payment must have required property '@ondc/org/settlement_basis'
- /message/order/payment must have required property '@ondc/org/settlement_window'
- /message/order/payment must have required property '@ondc/org/withholding_amount'

@ShippuYadav

**Comment by ShippuYadav** [comment] 2023-10-24 13:42
Please check latest PR https://github.com/ONDC-Official/v1.2.0-logs/pull/60
@sharmasahil0331

**Comment by sharmasahil0331** [comment] 2023-10-25 12:16
**confirm**

- /message/order/payment must have required property '@ondc/org/settlement_basis'
- /message/order/payment must have required property '@ondc/org/settlement_window'
- /message/order/payment must have required property '@ondc/org/withholding_amount'

**on_confirm**

- payment object mismatches in /confirm & /on_confirm

**common**

- value of address.name, address.building and address.locality should be unique
- /message/order/fulfillments/0 must have required property 'tracking'


@ShippuYadav

**Comment by ShippuYadav** [comment] 2023-10-25 18:06
Please check latest PR https://github.com/ONDC-Official/v1.2.0-logs/pull/63
@sharmasahil0331

**Comment by sharmasahil0331** [comment] 2023-10-28 09:42
**on_search_full_catalog**

- locality and street cannot be same in /message/catalog/bpp_providers/locations/address

**search_inc_catalog**

- /message/catalog should not contain fulfillment object

**on_confirm**

- value of tax_number in message/order/tags/code/bap_terms should be same as the value passed in confirm call

@ShippuYadav

**Comment by ShippuYadav** [comment] 2023-10-28 10:15
@sharmasahil0331 /message/catalog should not contain fulfillment object - I have not send fulfillment object inside inc search, Please clear this point.
@sharmasahil0331 Please review this latest PR https://github.com/ONDC-Official/v1.2.0-logs/pull/74

**Comment by ShippuYadav** [comment] 2023-11-01 13:22
@sharmasahil0331 Please check latest  https://github.com/ONDC-Official/v1.2.0-logs/pull/86

**Comment by ensservices** [comment] 2023-11-03 06:17
@bluecypher Please check

**Comment by sharmasahil0331** [comment] 2023-11-06 11:43
**on_search_inc_refresh**

- /context/bpp_uri must match format url, it must includes https or www
- Message Id for /search_inc_refresh and /on_search_inc_refresh api should be same

@ShippuYadav

**Comment by ShippuYadav** [comment] 2023-11-06 13:34
@bluecypher  Please check this PR https://github.com/ONDC-Official/v1.2.0-logs/pull/98
@sharmasahil0331

**Comment by bluecypher** [comment] 2023-11-09 07:56
**/on_search**

- pincode related serviceability is currently not supported by the buyer apps; use either of hyperlocal or PAN India

**/on_search (incremental)**

- callback response should not take longer

**/on_confirm**

- estimated pickup and delivery time ranges can't be the same

**/on_status (Accepted)**

- order/updated_at should be updated as per the context/timestamp

**/on_status (Order-picked-up)**

- order/updated_at can't be earlier than pickup timestamp (/fulfillments/start/time/timestamp)

**/on_status (Order-delivered)**

- order/updated_at can't be earlier than delivery timestamp (/fulfillments/end/time/timestamp)

## Flow 3

- Not as per the test case scenario

@ShippuYadav

**Comment by ShippuYadav** [comment] 2023-11-11 10:23
@sharmasahil0331 @bluecypher Please check 
https://github.com/ONDC-Official/v1.2.0-logs/pull/116

**Comment by bluecypher** [comment] 2023-11-20 09:05
### - variant groups/variants should be provided for validation

### - Flow 4/5 in Group B should be submitted for validation

**/on_search**

- item.available.count should be either 99 (inventory available) or 0 (out-of-stock)
- item.maximum.count should be either default value 99 (no cap per order) or any other +ve value (cap per order)

**/init & /on_init**

- lat/lng are invalid attributes in /billing and /fulfillments

**/on_confirm**

- discrepancy in the estimated time ranges; delivery time can't be before pickup time

**/on_status (picked)**

- invalid attribute "document"; should be "documents"


@ShippuYadav

**Comment by ShippuYadav** [comment] 2023-11-22 13:18
I have fixed all the issue mentioned above
@sharmasahil0331 @bluecypher Please find latest PR https://github.com/ONDC-Official/v1.2.0-logs/pull/144

**Comment by sharmasahil0331** [comment] 2023-11-28 13:52
**/init & /on_init**

- lat/lng are invalid attributes in /billing

@ShippuYadav

**Comment by BLR-0118** [comment] 2023-12-07 15:15
@ShippuYadav

**Comment by BLR-0118** [comment] 2023-12-10 17:22
Also, request you to pls fix error.message in flow 3 (on_select_out_of_stock) to send message as per the new format in the contract;

**Comment by BLR-0118** [comment] 2023-12-10 17:23
@NJ-Nitank

**Comment by NJ-Nitank** [comment] 2023-12-11 13:04
@BLR-0118, Submitted updated logs for Ushop, https://github.com/ONDC-Official/v1.2.0-logs/pull/248

**Comment by BLR-0118** [comment] 2023-12-14 13:02
Flow 1:
1. /on_search:
- formatting is not removed - html tags replaced by bullet points;
Flow 3:
1. /on_select_out_of_stock:
- error.message not correct - check [here](https://github.com/ONDC-Official/v1.2.0-logs/blob/master/Bitsila/v1.2_logs_14_nov/GroupB/FLOW3/on_select_oos.json) & contract doc on how it should be encoded;
Flow 4 & 5:
- cancel & RTO flows are incorrect as it doesn't maintain the audit trail as per contract - check the contract doc on how the forward shipment fulfillment is cancelled & item qty count assigned to it becomes 0 & how a separate fulfillment of type "Cancel" is created to which items in forward shipment fulfillment is assigned;

**Comment by BLR-0118** [comment] 2023-12-14 13:02
@NJ-Nitank

**Comment by ShippuYadav** [comment] 2023-12-14 13:29
@BLR-0118 sir can you specify the issue of on_select_out_of_stock error.message, It is as per the documents


 
<img width="490" alt="Screenshot_8" src="https://github.com/ONDC-Official/v1.2.0-logs/assets/115714289/3e19d2ae-3b70-4895-9893-8b4ac46bd691">
<img width="377" alt="Screenshot_9" src="https://github.com/ONDC-Official/v1.2.0-logs/assets/115714289/fe0bb18a-5768-4176-9969-528df343a24f">
<img width="238" alt="Screenshot_7" src="https://github.com/ONDC-Official/v1.2.0-logs/assets/115714289/0301d0bc-66ea-49b5-9c77-11677944763a">

**Comment by NJ-Nitank** [comment] 2023-12-20 12:03
@BLR-0118 Sir, Here are the updated logs, Please review this PR
https://github.com/ONDC-Official/v1.2.0-logs/pull/309

**Comment by BLR-0118** [comment] 2023-12-25 18:00
1. /on_cancel flow is wrong for flow 4 but is correct for flow 5; pls fix flow 4 to show correct payload (multiple quote_trail objects within same fulfillment instead of creating 2 separate fulfillments with same id);
2. for /on_select & /on_init, can you add provider.locations to Order (similar to what's in /on_confirm);
3. remove order.provider_location;
also resubmit logs only for the above;

**Comment by BLR-0118** [comment] 2023-12-25 18:01
@NJ-Nitank

**Comment by NJ-Nitank** [comment] 2023-12-26 07:53
Hello Sir @BLR-0118, As per the feedback, we have changed in payload.Please review this PR https://github.com/ONDC-Official/v1.2.0-logs/pull/356

**Comment by BLR-0118** [comment] 2023-12-26 17:22
logs cleared for v1.2.0 for grocery (RET10)

**Comment by BLR-0118** [comment] 2023-12-26 17:22
@NJ-Nitank

**Closed by BLR-0118** 2023-12-26 17:22 UTC

**Comment by NJ-Nitank** [comment] 2023-12-26 17:35
@BLR-0118 Sir, Do we need to do it for fashion & BPC.

**Comment by BLR-0118** [comment] 2023-12-26 18:35
yes, you need to submit logs for /search & /on_search for these categories

**Comment by NJ-Nitank** [comment] 2023-12-29 17:11
@BLR-0118 Sir, Please review this PR for Fashion & BPC Category. https://github.com/ONDC-Official/v1.2.0-logs/pull/402
