### ISSUE TITLE
Dehaat (AGR10) BA- compliance check

### ISSUE THREAD

**Issue by sahil-ondc** [ONDC-Official/v1.2.0-logs#613] opened 2024-01-22 20:14 UTC
### search_full_catalog_refresh

- ttl = PT30S as per the API Contract
- Timestamp not in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) Format

### select

- /message/order/fulfillments/0/end/location must have required property 'address'
- ttl = PT30S as per the API Contract
- Timestamp not in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) Format

### init

- /message/order/items/0 must have required property 'fulfillment_id'
- /message/order/billing/address must have required property 'building'
- /message/order/fulfillments/0/end/location/address must have required property 'building'
- Timestamp not in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) Format
- address.area_code in fulfillments[0].end.location mismatch in /select & /init

### confirm

- /message/order must have required property 'tags'
- /message/order must have required property 'created_at'
- /message/order must have required property 'updated_at'
- /message/order/items/0 must have required property 'quantity'

**Comment by bluecypher** [comment] 2024-01-23 05:11
@skdeep12

**Comment by BLR-0118** [comment] 2024-03-22 07:09
closing, duplicate of #570

**Closed by BLR-0118** 2024-03-22 07:09 UTC
